name: Lint and Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files --show-diff-on-failure

      # This still does something weird, comment out for now
      #    - name: TF Provider Lint
      #      uses: bflad/tfproviderlint-github-action@master
      #      if: runner.os == 'Linux'
      #      with:
      #        args: "./..."

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os_arch:
          - linux/amd64
          - darwin/amd64
          - windows/amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: |
          GOOSARCH=${{ matrix.os_arch }}
          GOOS=${GOOSARCH%/*}
          GOARCH=${GOOSARCH#*/}

          NAME=${{github.repository}}-$GOOS-$GOARCH
          echo "MODULE_NAME=$NAME" >> $GITHUB_ENV

          GOOS=$GOOS GOARCH=$GOARCH go build -o $NAME -v

      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ${{ env.MODULE_NAME }}
